import os
import json
import logging
from typing import Dict, Any, List
from src.utils import get_logger

logger = get_logger("output_writer")

def write_outputs(
    data: Dict[str, Any],
    output_dir: str = "outputs",
    json_filename: str = "result.json",
    md_filename: str = "result.md"
) -> None:
    """
    Writes the insight pipeline results to both a JSON file and a Markdown file.
    
    Creates output_dir if it does not exist.
    """
    # Safeguard directory creation 
    os.makedirs(output_dir, exist_ok=True)
    
    json_path = os.path.join(output_dir, json_filename)
    md_path = os.path.join(output_dir, md_filename)
    
    # 1. Write JSON Output
    try:
        with open(json_path, "w", encoding="utf-8") as jf:
            json.dump(data, jf, indent=2, ensure_ascii=False)
        logger.info(f"Structured JSON output successfully written to: {json_path}")
    except Exception as e:
        logger.error(f"Failed to write JSON output to {json_path}: {e}")
        raise

    # 2. Generate and Write Markdown Output
    try:
        md_content = _generate_markdown(data)
        with open(md_path, "w", encoding="utf-8") as mf:
            mf.write(md_content)
        logger.info(f"Human-readable Markdown report successfully written to: {md_path}")
    except Exception as e:
        logger.error(f"Failed to write Markdown report to {md_path}: {e}")
        raise


def _generate_markdown(data: Dict[str, Any]) -> str:
    """Formats the pipeline result data dictionary into a clean Markdown document."""
    doc_name = data.get("document_name", "Unknown Document")
    total_chunks = data.get("total_chunks", 0)
    meta = data.get("metadata", {})
    
    # Header Section
    md = []
    md.append(f"# Document Insight Report: {doc_name}")
    md.append("")
    md.append("## 📊 Processing Metadata")
    md.append(f"- **File Name**: `{doc_name}`")
    md.append(f"- **Total logical chunks**: {total_chunks}")
    md.append(f"- **Model Used**: `{meta.get('model_used', 'N/A')}`")
    md.append(f"- **Processed At**: {meta.get('timestamp', 'N/A')}")
    md.append(f"- **Total execution time**: {meta.get('processing_time', 'N/A')}")
    md.append("")
    md.append("---")
    md.append("")
    
    # Section Summaries
    md.append("## 📝 Section-by-Section Summary")
    md.append("")
    
    summaries = data.get("sections_summary", [])
    if not summaries:
        md.append("_No summaries generated._")
    else:
        for idx, sec in enumerate(summaries, start=1):
            title = sec.get("section_title", f"Section {idx}")
            md.append(f"### 📍 {title}")
            bullets = sec.get("bullet_points", [])
            for pt in bullets:
                md.append(f"- {pt}")
            md.append("")
            
    md.append("---")
    md.append("")
    
    # Q&A Results
    md.append("## ❓ Document Q&A (Fact-Retrieval)")
    md.append("")
    
    qa = data.get("qa_results", [])
    if not qa:
        md.append("_No QA results generated._")
    else:
        for item in qa:
            question = item.get("question", "N/A")
            answer = item.get("answer", "N/A")
            ref = item.get("source_chunk_reference", "N/A")
            
            md.append(f"### 💬 Q: {question}")
            md.append(f"**A**: {answer}")
            md.append(f"> **Source Reference**: _{ref}_")
            md.append("")
            
    md.append("---")
    md.append("")
    md.append("_Report auto-generated by Mini Document Insight Pipeline._")
    
    return "\n".join(md)
